version: '3'


services:

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver_plus 0.0.0.0:8000"
    container_name: django_app
    environment:
        DJANGO_SETTINGS_MODULE: 'sample.settings.local'
    networks:
      ab_network:
        aliases:
          - 'djangoapp.local'
    volumes:
      - ./src:/src
      - ./media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: django_app_db
    networks:
      - ab_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


volumes:
  postgres_data:


networks:
  ab_network:
    external: true
